### ISSUE TITLE
CB 1.1-R3 (v2.4) Auto join bug?

### ISSUE THREAD

**Issue by aciidic** [mbax/VanishNoPacket#70]
I updated to v2.3, start playing and then 5 minutes later v2.4 comes out. I update to v2.4 and now every time I join I join invisible even though it was working absolutely fine in 2.3 and 2.2! EDIT: Same issue in 2.3! Am back to 2.2 and no problems..

Also I really think using permissions for this is a bad idea! It would be much more user friendly to define in config if to join vanished or specific players or ranks. Or even better a config file for each user and a toggle option!

Here are my permissionsEX:

```
Admin:
    prefix: '&a[Admin]&e '
    permissions:
    - -vanish.silentjoin # Join silently for regular users, on /vanish will announce join
    - -vanish.silentquit # Quit silently for regular users
    - -vanish.nointeract # Prevents pretty much everything you could do with either mouse button, as well as pressure pads. Includes block breaking, placing.
    - -vanish.nochat # Prevents you from accidentally chatting, including the /me command
    - -vanish.preventoutgoingdamage # Prevent accidentally hitting people/animals/monsters while invisible
    - '*'
```

Any ideas?
